# Generated by Django 5.2 on 2025-05-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="个人简介")),
                (
                    "personal_background",
                    models.ImageField(
                        blank=True,
                        default="personal_backgrounds/default.png",
                        null=True,
                        upload_to="personal_backgrounds/",
                        verbose_name="个人资料背景",
                    ),
                ),
                (
                    "page_background",
                    models.ImageField(
                        blank=True,
                        default="page_backgrounds/default.png",
                        null=True,
                        upload_to="page_backgrounds/",
                        verbose_name="页面背景",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
